server:
  port: 8800
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbprodutos?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: shtkal
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
